// Single source of truth for plans. Edit this file to change pricing/specs —
// everything else (checkout, provisioning, the pricing page) reads from here.
//
// eggId / nestId / locationId map to your Pterodactyl panel's IDs
// (Admin -> Nests/Eggs, Admin -> Locations). Find them in your panel's admin URLs.

module.exports = {
  free: {
    key: 'free',
    name: 'Create Your Free Server',
    tagline: '2 GB free forever — perfect for friends, testing, and small worlds.',
    priceCents: 0,
    interval: null,
    ramMb: 2048,
    diskMb: 10240,
    cpuPercent: 100,
    databases: 0,
    backups: 1,
    swapMb: 0,
    ioWeight: 500,
    nestId: Number(process.env.PTERO_NEST_ID_FREE || 1),
    eggId: Number(process.env.PTERO_EGG_ID_FREE || 1),
    locationId: Number(process.env.PTERO_LOCATION_ID_NA || 1),
    stripePriceId: null,
    limitPerAccount: 1,
  },
  starter: {
    key: 'starter',
    name: '4 GB Server',
    tagline: 'More power for small communities and growing worlds.',
    priceCents: 599,
    interval: 'month',
    ramMb: 4096,
    diskMb: 20480,
    cpuPercent: 200,
    databases: 1,
    backups: 3,
    swapMb: 0,
    ioWeight: 500,
    nestId: Number(process.env.PTERO_NEST_ID_PAID || 1),
    eggId: Number(process.env.PTERO_EGG_ID_PAID || 1),
    locationId: Number(process.env.PTERO_LOCATION_ID_NA || 1),
    stripePriceId: process.env.STRIPE_PRICE_STARTER || null,
    limitPerAccount: null,
  },
  pro: {
    key: 'pro',
    name: '8 GB Server',
    tagline: 'For public communities and heavier modpacks.',
    priceCents: 1199,
    interval: 'month',
    ramMb: 8192,
    diskMb: 40960,
    cpuPercent: 300,
    databases: 2,
    backups: 5,
    swapMb: 0,
    ioWeight: 700,
    nestId: Number(process.env.PTERO_NEST_ID_PAID || 1),
    eggId: Number(process.env.PTERO_EGG_ID_PAID || 1),
    locationId: Number(process.env.PTERO_LOCATION_ID_NA || 1),
    stripePriceId: process.env.STRIPE_PRICE_PRO || null,
    limitPerAccount: null,
  },
};
